version: '3'

networks:
  find3-network:
    driver: bridge

services:
  find3server:
    container_name: find3server
    #image: schollz/find3
    build: .
    restart: always
    volumes:
      - ./find3server:/data
      #- ./extra:/extra
    environment:
      - MQTT_ADMIN=admin
      - MQTT_PASS=1234
      - MQTT_SERVER='localhost:1883'
      - MQTT_EXTERNAL='10.20.11.175'
     #- MQTT_EXTERNAL='34.219.188.184'
      - MQTT_PORT=1883
    ports:
      - "11883:1883"
      - "8003:8003"
    networks:
      - find3-network
